### ISSUE TITLE
Relinking effect and Controller not reflected in frontend

### ISSUE THREAD

**Issue by shauneccles** [LedFx/frontend_v3#4]
Upon creating an effect and controller, if you connect them together they link correctly.

If you remove the link by using "x", no connector is shown on the front-end as expected.

Dragging from the effect to the controller again shows another `connect` API hit, and the config appears to update however the frontend does not reflect it despite refreshing.

**Comment by not-matt** [comment]
Fixed 
ledfx/ledfx_v3@317c4abe9b97bcaef1ce72ff3c6da52e4363e179
